# Generated by Django 4.2.16 on 2024-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0003_alter_detection_by_alter_detection_detection_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='feed_back',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
