# Generated by Django 4.2.16 on 2024-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0004_alter_detection_confidence_alter_detection_feed_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='class_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
