# Generated by Django 4.2.16 on 2024-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0005_detection_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='class_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
